[project]
name = "ASReview-NEMO"
description = "ASReview New Exciting Models"
readme = "README.md"
authors = [
    { name = "ASReview LAB developers", email = "asreview@uu.nl" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11"
]
keywords = ["systematic review"]
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "asreview>=1,<2",
    "xgboost",
    "sentence_transformers",
    "gensim",
    "numpy",
    "scikeras",
    "spacy",
    "scikit-learn",
    "tensorflow",
    "scipy"
]

[project.urls]
Issues = "https://github.com/asreview/asreview-nemo/issues"
Repository = "https://github.com/asreview/asreview-nemo/"

[build-system]
build-backend = 'setuptools.build_meta'
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[tool.setuptools]
packages = ["asreviewcontrib"]

[tool.setuptools_scm]
write_to = "asreviewcontrib/models/_version.py"

[project.entry-points."asreview.models.classifiers"]
"xgboost" = "asreviewcontrib.models.classifiers:XGBoost"
"nn-2-layer" = "asreviewcontrib.models.classifiers:NN2LayerClassifier"
"adaboost" = "asreviewcontrib.models.classifiers:AdaBoost"
"knn" = "asreviewcontrib.models.classifiers:KNN"
"dynamic-nn" = "asreviewcontrib.models.classifiers:DynamicNNClassifier"

[project.entry-points."asreview.models.feature_extraction"]
"sbert" = "asreviewcontrib.models.feature_extraction:SBERT"

[tool.ruff]
select = ["E", "F", "UP", "B"]

[tool.ruff.isort]
force-single-line = true