[project]
name = "ASReview-NEMO"
description = "ASReview New Exciting Models"
readme = "README.md"
authors = [
    { name = "ASReview LAB developers", email = "asreview@uu.nl" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
keywords = ["systematic review"]
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "asreview>=2",
    "xgboost",
    "sentence_transformers",
    "gensim",
    "numpy",
    "scikeras",
    "scikit-learn",
    "tensorflow",
    "scipy==1.12",
    "tf-keras"
]

[project.urls]
Issues = "https://github.com/asreview/asreview-nemo/issues"
Repository = "https://github.com/asreview/asreview-nemo/"

[build-system]
build-backend = 'setuptools.build_meta'
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[tool.setuptools]
packages = ["asreviewcontrib", "asreviewcontrib.nemo_models", "asreviewcontrib.nemo"]

[tool.setuptools_scm]
write_to = "asreviewcontrib/nemo/_version.py"

[project.entry-points."asreview.models.classifiers"]
"xgboost" = "asreviewcontrib.nemo_models.classifiers:XGBoost"
"nn-2-layer" = "asreviewcontrib.nemo_models.classifiers:NN2LayerClassifier"
"adaboost" = "asreviewcontrib.nemo_models.classifiers:AdaBoost"
"dynamic-nn" = "asreviewcontrib.nemo_models.classifiers:DynamicNNClassifier"

[project.entry-points."asreview.models.feature_extraction"]
"sbert" = "asreviewcontrib.nemo_models.feature_extraction:SBERT"
"doc2vec" = "asreviewcontrib.nemo_models.feature_extraction:Doc2Vec"
"mxbai" = "asreviewcontrib.nemo_models.feature_extraction:MXBAI"
"labse" = "asreviewcontrib.nemo_models.feature_extraction:LaBSE"

[project.entry-points."asreview.entry_points"]
nemo = "asreviewcontrib.nemo.entrypoint:NemoEntryPoint"

[tool.ruff]
select = ["E", "F", "UP", "B"]

[tool.ruff.isort]
force-single-line = true
