name: Install Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'
    - name: Install package
      run: |
        pip install .
    - name: Run ASReview checks
      run: |
        python -c "
        import asreview
        from asreview.feature_extraction import list_feature_extraction
        from asreview.classifiers import list_classifiers

        feature_extractions = list_feature_extraction()
        classifiers = list_classifiers()

        pre_made_feature_extractions = ['sbert', 'doc2vec', 'multilingual', 'labse', 'spacy', 'scaled-doc2vec', 'mxbai']
        pre_made_classifiers = ['xgboost', 'nn-2-layer', 'adaboost', 'knn', 'dynamic-nn']

        feature_extractions_match = (feature_extractions == pre_made_feature_extractions)
        classifiers_match = (classifiers == pre_made_classifiers)

        print('Feature Extractions:', feature_extractions)
        print('Classifiers:', classifiers)
        print('Feature Extractions Match:', feature_extractions_match)
        print('Classifiers Match:', classifiers_match)
        "
