name: Install Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        architecture: 'x64'
    - name: Install package
      run: |
        pip install .
    - name: Run ASReview checks
      run: |
        python -c "
        import asreview
        from asreview.models.feature_extraction import list_feature_extraction
        from asreview.models.classifiers import list_classifiers

        feature_extractions = list_feature_extraction()
        classifiers = list_classifiers()

        print('Feature Extractions:', feature_extractions)
        print('Classifiers:', classifiers)
        "
